### ISSUE TITLE
Nuget configuration incomplete

### ISSUE THREAD

**Issue by jbeeko** [deepcovelabs/raven-sdk-dotnet#2]
Nuget needs to have a link to correct license file. Is it possible/reasonable to link to one on GitHub?
Nuget should also link to docs branch on github, or failing that to the readme under the field "Project Site". Like this

![image](https://cloud.githubusercontent.com/assets/4968704/15332858/2c66c32a-1c1c-11e6-9869-e98b0fae8432.png)

**Comment by kevinneufeld** [comment]
fixed, latest release
